[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.58.3"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[[redirects]]
  from = "https://posdefecology.netlify.com/*"
  to = "https://www.posdefecology.net/:splat"
  status = 301
  force = true
